### ISSUE TITLE
Update to use AbstractInterpreter framework

### ISSUE THREAD

**Issue by Keno** [JuliaDebug/Cthulhu.jl#124]
Cthulhu should ideally be updated to use an `AbstractInterpreter` to do a full inference from the call site and then just be an interactive utility to explore what inference actually did. At the moment if inference does things like limiting call cycles, Cthulhu will re-do inference on descend and give a misleading view of the quality of type information. An additional benefit of using the AbstractInterpreter framework would be that Cthulhu could expose inference remarks. Perhaps @aviatesk would be interested in looking at this, since JET.jl is somewhat similar.

**Comment by vchuravy** [comment]
One of the challenges here is composability of `AbstractInterpreter`'s I don't want to lose the ability to use Cthulhu over CUDA.jl

cc: @maleadt
