### ISSUE TITLE
code printing contains numerous mistakes in numbering?

### ISSUE THREAD

**Issue by vtjnash** [JuliaDebug/Cthulhu.jl#153]
On https://github.com/vtjnash/julia/pull/new/jn/multireplacer commit a5b3b28381246ce38942a84781ec5776db219993, I noticed when testing the new code with `@descend optimize=true replace("s", 'c'=>"BOOM");` that descending into this function shows numerous incorrect SSAValues of the form:
```
85 ── %171 = goto #101
```

**Comment by simeonschaub** [comment]
This doesn't seem to be a printing problem, but looks like Cthulhu is producing corrupt IR. If I add the following to `cthulhu_typed`
```diff
diff --git a/src/codeview.jl b/src/codeview.jl
index 0344452..a8c97f8 100644
--- a/src/codeview.jl
+++ b/src/codeview.jl
@@ -96,6 +96,7 @@ end
 
 
 function cthulu_typed(io::IO, debuginfo, src, rt, mi, iswarn, stable_code)
+    src isa IRCode && Core.Compiler.verify_ir(src)
     debuginfo = IRShow.debuginfo(debuginfo)
     lineprinter = __debuginfo[debuginfo]
     rettype = ignorelimited(rt)
```
I get the following error:
```
Block 9 successors (Array{Int64, (1,)}[10]), does not match GotoIfNot terminator
```

**Comment by vchuravy** [comment]
This might then be a bug in DCE?
