### ISSUE TITLE
This recording has been archived

### ISSUE THREAD

**Issue by cossio** [JuliaDebug/Cthulhu.jl#25]
This is from the Readme:

![image](https://user-images.githubusercontent.com/10637482/53528620-24f5e900-3ab8-11e9-939d-eba40f7fd1b7.png)

From asciicinema.org:

> This recording has been archived
> 
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by vchuravy** [comment]
I should probably fix that ;)....

**Comment by DilumAluthge** [comment]
Bump. @vchuravy Could you update the recording in the README?

**Comment by chakravala** [comment]
This recording has been archived. Any update on that?

**Comment by KristofferC** [comment]
The recording has been removed from the readme.
