### ISSUE TITLE
`@descend` doesn't work in indexing with `begin` or `end`

### ISSUE THREAD

**Issue by jishnub** [JuliaDebug/Cthulhu.jl#291]
```julia
julia> a = rand(2);

julia> @descend a[begin:end]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1

julia> @descend a[1:end]
ERROR: UndefVarError: end not defined
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

Would be great if the expression could be lowered before being passed to `@descend`

**Comment by aviatesk** [comment]
Probably better to be raised at https://github.com/JuliaLang/julia as the same issue happens for `@code_typed` and its family. `@descend` uses the same internal utility as them.

**Comment by aviatesk** [comment]
Ian fixed this issue in the upstream.
