### ISSUE TITLE
can't find descend_clicked

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaDebug/Cthulhu.jl#378]
Tim watching your video: https://youtu.be/pvduxLowpPY on fixing performance issues. But looks like `descend_clicked()` is missing 🥲

```
1.9.0-beta3>.\sort.jl:1009, MethodInstance for Base.Sort.partition!(::Vector{Any}, ::Int64, ::Int64, ::Int64, ::Base.Order.ForwardOrdering, ::Vector{Any}, ::Bool, ::Vector{Any}, ::Int64)
1.9.0-beta3>

1.9.0-beta3>using Cthulhu

1.9.0-beta3>descend_clicked()
ERROR: UndefVarError: `descend_clicked` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[25]:1
```

**Comment by timholy** [comment]
It's defined in ProfileView (it calls descend on a bar clicked in ProfileView). Make sure you're running ProfileView 1.7.0 or higher.

**Comment by timholy** [comment]
Keep in mind that you need it only if you want to get there via ProfileView. Otherwise, Cthulhu's `@descend` should work very nicely (see the [README](https://github.com/JuliaDebug/Cthulhu.jl)).

**Comment by AbhimanyuAryan** [comment]
Thanks

**Comment by AbhimanyuAryan** [comment]
@timholy sorry to bother you again. I am now on everything master

```
Cthulhu v2.8.2 `C:\Users\aryan\.julia\dev\Cthulhu`
ProfileView v1.7.0 `C:\Users\aryan\.julia\dev\ProfileView`
```

I can see `descend_clicked` exported properly in the source code. But it still shows me this error

```
1.9.0-beta3>descend_clicked()
ERROR: UndefVarError: `descend_clicked` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[60]:1
```

no idea why that's happening

**Comment by AbhimanyuAryan** [comment]
But I wasn't presented with this option of installing Cthulhu. So I instead dev'ed it. Looks like that's the issue. It's still using old version of Cthulu which was @required during ProfileView installation 

<img width="542" alt="test" src="https://user-images.githubusercontent.com/8083613/224513195-1550d247-58db-4cad-9f59-084882640cd1.png">

**Comment by AbhimanyuAryan** [comment]
yes infact that was the problem. It was using old verison of package somehow. I had to delete everything and than `__init__` properly required cthulhu package
