### ISSUE TITLE
Print type instability colors in descent menu

### ISSUE THREAD

**Issue by staticfloat** [JuliaDebug/Cthulhu.jl#39]
I love the type instability colors while descending; often times I am simply chasing the red down into the endless abyss; it would be great if we could accelerate my fall by printing the red text style in the descent multiple-choice menu as well, so I don't need to look for `::Any` at the end of the call; I can simply let my primitive hind-brain steer me down.

**Comment by timholy** [comment]
This isn't as important now as it once was (now that we have `[h]ide type-stable statements`), but it still seemed worth doing. Will be fixed by #203.
