### ISSUE TITLE
`ERROR: unexpected broadcast` in `TypedSyntaxNode()` with multiple dot operators and composite type

### ISSUE THREAD

**Issue by mitchvanvuren** [JuliaDebug/Cthulhu.jl#415]
Hello, I'll start by saying that I do a lot of scientific computing and have been enjoying using Cthulhu to hunt down type instabilities, much appreciation for everyone working on the package.

This issue was originally encountered when using `@descend` but has since been isolated to `TypedSyntaxNode()` (see [this](https://www.reddit.com/r/Julia/comments/1201dz3/cthulhujl_multiple_dot_operators_and_composite/) thread on r/Julia).

MWE:
```
using TypedSyntax

struct foo
    bar::Float64
    foo(bar) = new(bar)
end

function not_working(foo,x)
    return (x.+2.0).+foo.bar
end

TypedSyntaxNode(not_working, (foo, Float64))
```

I believe this example is "minimal" in the sense that removing either dot operator, changing the order, removing the composite type, and broadcasting the dot operator all eliminate the error. All of the below run w/o issue.

```
function working1(foo,x)
    return (x.+2.0)+foo.bar
end
function working2(foo,x)
    return (x+2.0).+foo.bar
end
function working3(foo,x)
    return (x.+foo.bar).+2.0
end
function working4(foo,x)
    return (x.+2.0).+foo #Make sure to feed a Float64, not a foo
end
function working5(foo,x)
    return @.((x+2.0)+foo.bar)
end

TypedSyntaxNode(working1, (foo, Float64))
TypedSyntaxNode(working2, (foo, Float64))
TypedSyntaxNode(working3, (foo, Float64))
TypedSyntaxNode(working4, (Float64, Float64))
TypedSyntaxNode(working5, (foo, Float64))
```
It's also worth noting that while I use `+()` in this example, the same results held for any operator or combination of operators that I tried.

For my specific use-case, `@.` is a sufficient workaround, but I figured this issue was still useful/worth opening.

**Comment by timholy** [comment]
Thanks for the clean test case! New release coming shortly.
