### ISSUE TITLE
Cthulhu can't retrieve source in package extension?

### ISSUE THREAD

**Issue by gdalle** [JuliaDebug/Cthulhu.jl#478]
I'm sorry I don't have an MWE yet, but I tried Cthulhu for the first time on a package extension and it seems unable to retrieve source code for a method defined there. Instead it's showing me typed or lowered code. Any reason why that could be?

**Comment by vchuravy** [comment]
Cthulhu uses Revises system here, so maybe @timholy has an idea

**Comment by timholy** [comment]
Have a MWE by any chance?

**Comment by gdalle** [comment]
I'll set up a repo

**Comment by gdalle** [comment]
Wasn't able to reproduce, closing
