### ISSUE TITLE
Should types be annotated with their type by Cthulhu

### ISSUE THREAD

**Issue by Zentrik** [JuliaDebug/Cthulhu.jl#482]
E.g. For `f(x) = Dict{String}(x)`, descending on `f` with `x` a `String` produces
```jl
1 f(x::String) = Dict::Type{Dict}{String::Type{String}}::Type{Dict{String}}(x::String)
```
It's hard to read and seems unnecessary to annotate `Dict`, `String` and `Dict{String}` with `::Type{Dict}`, `::Type{String}`, `::Type{Dict{String}}`. Perhaps if the type is not an alias we could omit the annotation.

**Comment by Zentrik** [comment]
#465 seems related

**Comment by timholy** [comment]
An expanded case:

```julia
julia> MyDict{T} = Dict{T,Any}
Dict{T, Any} where T

julia> f(x) = MyDict{String}(x)
f (generic function with 1 method)

julia> using Cthulhu
[ Info: Precompiling Cthulhu [f68482b8-f384-11e8-15f7-abe071a5a75f]

julia> @descend f(["foo"=>7])
f(x) @ Main REPL[2]:1
1 f(x::Vector{Pair{String, Int64}})::Dict{String, Any} = MyDict::Type{Dict{T, Any} where T}{String::Type{String}}::Type{Dict{String, Any}}(x::Vector{Pair{String, Int64}})
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
 • MyDict::Type{Dict{T, Any} where T}{String::Type{String}}::Type{Dict{String, Any}}(x::Vector{Pair{String, Int64}})
   ↩
```

I'd agree that I don't want `String::Type{String}` printed. What about `MyDict::Type{Dict{T, Any} where T}`? If we'd like to print that, then we probably need to compare the display of the node to type? Some relevant `node` and `T` pairs:
- `(curly MyDict String) => Type{Dict{String, Any}}` (outer expression)
- `MyDict => Type{Dict{T, Any} where T}` (inner expression)
- `String => Type{String}` (inner parameter)

I almost wonder if the best implementation would be to print both the source-text and the annotation to a temporary buffer and then match on `"$str::Type{$str}"`. If it's a match, skip printing the type. Thoughts?

**Comment by Zentrik** [comment]
I do think we should print `MyDict::Type{Dict{T, Any} where T}`. It might be best to match on `"$str::Type{$str}"` as I think It will be fairly complicated otherwise. This is what I had for `String => Type{String}`, https://github.com/Zentrik/Cthulhu.jl/commit/1935375c5cf133f34713b5e146c994a3dba36a4e and this doesn't seem to even work all the time (also crashes on `T = Type{Union()}`).
