### ISSUE TITLE
Confusing text in README

### ISSUE THREAD

**Issue by DanielVandH** [JuliaDebug/Cthulhu.jl#507]
In https://github.com/JuliaDebug/Cthulhu.jl#viewing-the-internal-representation-of-julia-code, the section starts as

> Anyone using Cthulhu to investigate the behavior of Julia's compiler will prefer to examine the While Cthulhu tries to place type-annotations...

It looks like one of these sentences was accidentally copied over the other. I think "Anyone using Cthulhu to investigate the behavior of Julia's compiler will prefer to examine the" can just be removed? Not sure.

**Comment by timholy** [comment]
Thanks!
