### ISSUE TITLE
Inlay hint display for juxtaposition and infix operators

### ISSUE THREAD

**Issue by jariji** [JuliaDebug/Cthulhu.jl#532]
The inlay hints look a bit odd for juxtaposition and infix operators. I don't know if there's a standard way to display these in other languages that have inlay hints, so I don't have a solution, just pointing out the issue for discussion.

For juxtaposition, it just juxtaposes the hints:

```jl
f(x) = 2x

@descend f(3.0)
```

![image](https://github.com/JuliaDebug/Cthulhu.jl/assets/96840304/5217f8d0-5ccc-4003-9d8f-45e7f960500c)

and for infix operations it puts the hint on the operator:

```jl
f(x) = 2*x

@descend f(3.0)
```

![image](https://github.com/JuliaDebug/Cthulhu.jl/assets/96840304/9a1596f1-f662-4278-a950-d1b069e5fec6)

```
(jl_ObndQM) pkg> st
Status `/tmp/jl_ObndQM/Project.toml`
  [f68482b8] Cthulhu v2.10.0

julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900XT 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 35 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 24
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  LD_LIBRARY_PATH = :/lib
  JULIA_EDITOR = code

VSCode Julia 1.65.2
VSCode 1.84.2
Linux 6.6.8
```

**Comment by Zentrik** [comment]
The inlay hints are supposed to just replicate what Cthulhu prints in the REPL. Do they print differently in the REPL? Otherwise this is a more general problem.

**Comment by jariji** [comment]
Looks different:

```jl
julia> @descend f(3.0)
f(x) @ Main REPL[2]:1
1 f(x::Float64)::Float64 = 2x::Float64

julia> @descend f(3.0)
f(x) @ Main REPL[4]:1
1 f(x::Float64)::Float64 = 2*x::Float64


(tmp.6EvBOOSOSW) pkg> st
Status `/tmp/tmp.6EvBOOSOSW/Project.toml`
  [f68482b8] Cthulhu v2.10.0
```

**Comment by Zentrik** [comment]
I'm struggling to reproduce this, could you make sure you're on the latest version (1.2.4) of TypedSyntax. Also what are your Cthulhu settings, i.e. mine have warnings off, don't hide type-stable statements, etc.
```julia
julia> @descend f(3.0)
f(x) @ Main /media/rag/NVME/Code/Cthulhu.jl/tmp.jl:1
1 f(x::Float64)::Float64 = 2x::Float64
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native, [j]ump to source always, [v]scode: inlay types, [V]scode: diagnostics.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
 • 2x::Float64
   ↩
```
I'm on a slightly newer version of VSCode, 1.85.1, but I fail to see why that would make a difference.

**Comment by jariji** [comment]
Upgrading TypedSyntax 1.2.3 -> 1.2.4 solved it. Cheers.

![image](https://github.com/JuliaDebug/Cthulhu.jl/assets/96840304/d16318cc-5025-4a87-99ae-057c9c6b1ad5)
![image](https://github.com/JuliaDebug/Cthulhu.jl/assets/96840304/7dc39e1d-4b45-473e-91da-fe83282524c2)
