### ISSUE TITLE
Add CI for Arm Macs

### ISSUE THREAD

**Issue by Zentrik** [JuliaDebug/Cthulhu.jl#538]
Armv8 Macs should be the only tier 1 platform, according to https://julialang.org/downloads/, that CI doesn't run on after #529.
I'm not sure if GitHub has Arm Mac runners.

**Comment by fingolfin** [comment]
When you posted this, ARM runners for macOS were in beta, but I think they are now generally available (possibly even the default when using `macos-latest` w/o specifying an architecture?)

**Comment by simeonschaub** [comment]
Yes, you can see here that we're actually using the arm64 runners: https://github.com/JuliaDebug/Cthulhu.jl/actions/runs/10724948705/job/29741733381#step:1:8 (though the job is still misleadingly called x64)
