### ISSUE TITLE
Duplicate Inlay Hints when Language server is providing type hints

### ISSUE THREAD

**Issue by Zentrik** [JuliaDebug/Cthulhu.jl#542]
If the LanguageServer provides type hints then Cthulhu will also provide that hint causing a duplicate.

Not sure how to fix this yet.

**Comment by pfitzseb** [comment]
An easy but not particularly satisfactory fix would be to disable the static inline hints when Cthulhu pushes its hints. I'll prepare a PR for that and tag you.

**Comment by Zentrik** [comment]
Thanks
