### ISSUE TITLE
ERROR: LoadError: Some tests did not pass: 320 passed, 1 failed, 0 errored, 1 broken.

### ISSUE THREAD

**Issue by iajzenszmi** [JuliaDebug/Cthulhu.jl#569]
ERROR: LoadError: Some tests did not pass: 320 passed, 1 failed, 0 errored, 1 broken.
in expression starting at /home/ian/.julia/packages/Cthulhu/r48vc/test/runtests.jl:3
ERROR: Package Cthulhu errored during testing

(@v1.10) pkg>

**Comment by simeonschaub** [comment]
Without more details on why the tests failed this doesn't really seem actionable
