### ISSUE TITLE
Possible bugfix (?)

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaDebug/Cthulhu.jl#88]
I have encountered a bug in Cthulhu in a relatively convoluted code. Changing this line: https://github.com/JuliaDebug/Cthulhu.jl/blob/f71e27a32dbf865c83f8ccab55239a25f3611636/src/reflection.jl#L114 to
`if !(t <: Tuple) || t isa Union || t isa UnionAll` seems to fix it. Does this make sense? I don't think I can find a simple way to reproduce my problem but it complained about `UnionAll` not having `parameters` field a few lines below.

**Comment by timholy** [comment]
The code base has essentially been rewritten for Julia 1.7 so I suspect this should be closed.
